const staticImages = [
{ id: 1 , name: 'ad perales del rio', path: 'https://www.todovoleibol.com/images/escudos/ad-perales-del-rio.jpg' },
{ id: 2 , name: 'cv majadahonda', path: 'https://www.todovoleibol.com/images/escudos/cv-majadahonda.jpg' },
{ id: 3 , name: 'cde voleibol colmenar', path: 'https://www.todovoleibol.com/images/escudos/cde-voleibol-colmenar.jpg' },
{ id: 4 , name: 'cde voleibol algete', path: 'https://www.todovoleibol.com/images/escudos/cde-voleibol-algete.jpg' },
{ id: 5 , name: 'c d e villa de ajalvir', path: 'https://www.todovoleibol.com/images/escudos/c-d-e-villa-de-ajalvir.jpg' },
{ id: 6 , name: 'cde voleibol madrid ciudad', path: 'https://www.todovoleibol.com/images/escudos/cde-voleibol-madrid-ciudad.jpg' },
{ id: 7 , name: 'cde m 2 de mayo', path: 'https://www.todovoleibol.com/images/escudos/cde-m-2-de-mayo.jpg' },
{ id: 8 , name: 'cde highlands el encinar', path: 'https://www.todovoleibol.com/images/escudos/cde-highlands-el-encinar.jpg' },
{ id: 9 , name: 'ancora galapagar', path: 'https://www.todovoleibol.com/images/escudos/ancora-galapagar.jpg' },
{ id: 10, name: 'cde chamartin vergara', path: 'https://www.todovoleibol.com/images/escudos/cde-chamartin-vergara.jpg' },
{ id: 11, name: 'cdb las nieves sports', path: 'https://www.todovoleibol.com/images/escudos/cdb-las-nieves-sports.jpg' },
{ id: 12, name: 'ad voleibol rivas', path: 'https://www.todovoleibol.com/images/escudos/ad-voleibol-rivas.jpg' },
{ id: 13, name: 'abv boadilla', path: 'https://www.todovoleibol.com/images/escudos/abv-boadilla.jpg' },
{ id: 14, name: 'cde voleibol getafe', path: 'https://www.todovoleibol.com/images/escudos/cde-voleibol-getafe.jpg' },
{ id: 15, name: 'cd gredos san diego', path: 'https://www.todovoleibol.com/images/escudos/cd-gredos-san-diego.jpg' },
{ id: 16, name: 'c d san patricio', path: 'https://www.todovoleibol.com/images/escudos/c-d-san-patricio.jpg' },
{ id: 17, name: 'c d e polideportivo los molinos', path: 'https://www.todovoleibol.com/images/escudos/c-d-e-polideportivo-los-molinos.jpg' },
{ id: 18, name: 'cde intervoley fuenlabrada', path: 'https://www.todovoleibol.com/images/escudos/cde-intervoley-fuenlabrada.jpg' },
{ id: 19, name: 'ad joigny', path: 'https://www.todovoleibol.com/images/escudos/ad-joigny.jpg' },
{ id: 20, name: 'cde arganvoley', path: 'https://www.todovoleibol.com/images/escudos/cde-arganvoley.jpg' },
{ id: 21, name: 'club deportivo educa play', path: 'https://www.todovoleibol.com/images/escudos/club-deportivo-educa-play.jpg' },
{ id: 22, name: 'cde asuncion', path: 'https://www.todovoleibol.com/images/escudos/cde-asuncion.jpg' },
{ id: 23, name: 'cd san agustin los negrales', path: 'https://www.todovoleibol.com/images/escudos/cd-san-agustin-los-negrales.jpg' },
{ id: 24, name: 'cde voleibol san fernando', path: 'https://www.todovoleibol.com/images/escudos/cde-voleibol-san-fernando.jpg' },
{ id: 25, name: 'cde parla voley', path: 'https://www.todovoleibol.com/images/escudos/cde-parla-voley.jpg' },
{ id: 26, name: 'cd sek ciudalcampo', path: 'https://www.todovoleibol.com/images/escudos/cd-sek-ciudalcampo.jpg' },
{ id: 27, name: 'club deportivo newman', path: 'https://www.todovoleibol.com/images/escudos/club-deportivo-newman.jpg' },
{ id: 28, name: 'club voleibol plaza castilla', path: 'https://www.todovoleibol.com/images/escudos/club-voleibol-plaza-castilla.jpg' },
{ id: 29, name: 'club deportivo elemental yma sports', path: 'https://www.todovoleibol.com/images/escudos/club-deportivo-elemental-yma-sports.jpg' },
{ id: 30, name: 'club saint louis des francais', path: 'https://www.todovoleibol.com/images/escudos/club-saint-louis-des-francais.jpg' },
{ id: 31, name: 'club nuestra senora del pilar', path: 'https://www.todovoleibol.com/images/escudos/club-nuestra-senora-del-pilar.jpg' },
{ id: 32, name: 'club irlandesas', path: 'https://www.todovoleibol.com/images/escudos/club-irlandesas.jpg' },
{ id: 33, name: 'colegio fuentelarreyna', path: 'https://www.todovoleibol.com/images/escudos/colegio-fuentelarreyna.jpg' },
{ id: 34, name: 'colegio americano', path: 'https://www.todovoleibol.com/images/escudos/colegio-americano.jpg' },
{ id: 35, name: 'cde voley playa madrid', path: 'https://www.todovoleibol.com/images/escudos/cde-voley-playa-madrid.jpg' },
{ id: 36, name: 'club voleibol aranjuez', path: 'https://www.todovoleibol.com/images/escudos/club-voleibol-aranjuez.jpg' },
{ id: 37, name: 'gmadrid sports', path: 'https://www.todovoleibol.com/images/escudos/gmadrid-sports.jpg' },
{ id: 38, name: 'club voleibol torrelodones', path: 'https://www.todovoleibol.com/images/escudos/club-voleibol-torrelodones.jpg' },
{ id: 39, name: 'club voleibol guadarrama', path: 'https://www.todovoleibol.com/images/escudos/club-voleibol-guadarrama.jpg' },
{ id: 40, name: 'club deportivo basico sek el castillo', path: 'https://www.todovoleibol.com/images/escudos/club-deportivo-basico-sek-el-castillo.jpg' },
{ id: 41, name: 'cde sanagus team voley', path: 'https://www.todovoleibol.com/images/escudos/cde-sanagus-team-voley.jpg' },
{ id: 42, name: 'cde voleibol soto', path: 'https://www.todovoleibol.com/images/escudos/cde-voleibol-soto.jpg' },
{ id: 43, name: 'block out beach volley', path: 'https://www.todovoleibol.com/images/escudos/block-out-beach-volley.jpg' },
{ id: 44, name: 'cde everest school', path: 'https://www.todovoleibol.com/images/escudos/cde-everest-school.jpg' },
{ id: 45, name: 'cd vallecas', path: 'https://www.todovoleibol.com/images/escudos/cd-vallecas.jpg' },
{ id: 46, name: 'ad estrecho tetuan', path: 'https://www.todovoleibol.com/images/escudos/ad-estrecho-tetuan.jpg' },
{ id: 47, name: 'club unificado voleibol alcorcon', path: 'https://www.todovoleibol.com/images/escudos/club-unificado-voleibol-alcorcon.jpg' },
{ id: 48, name: 'stars sport volley', path: 'https://www.todovoleibol.com/images/escudos/stars-sport-volley.jpg' },
{ id: 49, name: 'cv arganda', path: 'https://www.todovoleibol.com/images/escudos/cv-arganda.jpg' },
{ id: 50, name: 'cd san ignacio torrelodones', path: 'https://www.todovoleibol.com/images/escudos/cd-san-ignacio-torrelodones.jpg' },
{ id: 51, name: 'san agustin', path: 'https://www.todovoleibol.com/images/escudos/san-agustin.jpg' },
{ id: 52, name: 'sad recuerdo', path: 'https://www.todovoleibol.com/images/escudos/sad-recuerdo.jpg' },
{ id: 53, name: 'marianistas amoros', path: 'https://www.todovoleibol.com/images/escudos/marianistas-amoros.jpg' },
{ id: 54, name: 'mintonette cv pozuelo', path: 'https://www.todovoleibol.com/images/escudos/mintonette-cv-pozuelo.jpg' },
{ id: 55, name: 'cde voleibol valdemoro', path: 'https://www.todovoleibol.com/images/escudos/cde-voleibol-valdemoro.jpg' },
{ id: 56, name: 'cv sanse', path: 'https://www.todovoleibol.com/images/escudos/cv-sanse.jpg' },
{ id: 57, name: 'seccion de accion deportiva fusp ceu comunidad de madrid', path: 'https://www.todovoleibol.com/images/escudos/seccion-de-accion-deportiva-fusp-ceu-comunidad-de-madrid.jpg' },
{ id: 58, name: 'cv coslada', path: 'https://www.todovoleibol.com/images/escudos/cv-coslada.jpg' },
{ id: 59, name: 'corazonistas', path: 'https://www.todovoleibol.com/images/escudos/corazonistas.jpg' },
{ id: 60, name: 'cv nueva castilla', path: 'https://www.todovoleibol.com/images/escudos/cv-nueva-castilla.jpg' },
{ id: 61, name: 'madrid beach voley academy', path: 'https://www.todovoleibol.com/images/escudos/madrid-beach-voley-academy.jpg' },
{ id: 62, name: 'club union deportiva loeches', path: 'https://www.todovoleibol.com/images/escudos/club-union-deportiva-loeches.jpg' },
{ id: 63, name: 'club salesianos san miguel', path: 'https://www.todovoleibol.com/images/escudos/club-salesianos-san-miguel.jpg' },
{ id: 64, name: 'cd loreto madrid', path: 'https://www.todovoleibol.com/images/escudos/cd-loreto-madrid.jpg' },
{ id: 65, name: 'cd dosa', path: 'https://www.todovoleibol.com/images/escudos/cd-dosa.jpg' },
{ id: 66, name: 'cd ciudad de los muchachos', path: 'https://www.todovoleibol.com/images/escudos/cd-ciudad-de-los-muchachos.jpg' },
{ id: 67, name: 'club deportivo elemental aquila', path: 'https://www.todovoleibol.com/images/escudos/club-deportivo-elemental-aquila.jpg' },
{ id: 68, name: 'cde vb villanueva del pardillo', path: 'https://www.todovoleibol.com/images/escudos/cde-vb-villanueva-del-pardillo.jpg' },
{ id: 69, name: 'agrupacion padre manyanet', path: 'https://www.todovoleibol.com/images/escudos/agrupacion-padre-manyanet.jpg' },
{ id: 70, name: 'cv el escorial', path: 'https://www.todovoleibol.com/images/escudos/cv-el-escorial.jpg' },
{ id: 71, name: 'cde switch volley', path: 'https://www.todovoleibol.com/images/escudos/cde-switch-volley.jpg' },
{ id: 72, name: 'cde manzanares voley', path: 'https://www.todovoleibol.com/images/escudos/cde-manzanares-voley.jpg' },
{ id: 73, name: 'cdb grupo deportivo las rozas', path: 'https://www.todovoleibol.com/images/escudos/cdb-grupo-deportivo-las-rozas.jpg' },
{ id: 74, name: 'sad colegio internacional kolbe', path: 'https://www.todovoleibol.com/images/escudos/sad-colegio-internacional-kolbe.jpg' },
{ id: 75, name: 'cv torrejon', path: 'https://www.todovoleibol.com/images/escudos/cv-torrejon.jpg' },
{ id: 76, name: 'cv fuenlabrada', path: 'https://www.todovoleibol.com/images/escudos/cv-fuenlabrada.jpg' },
{ id: 77, name: 'cv mostoles', path: 'https://www.todovoleibol.com/images/escudos/cv-mostoles.jpg' },
{ id: 78, name: 'sad colegio claret', path: 'https://www.todovoleibol.com/images/escudos/sad-colegio-claret.jpg' },
{ id: 79, name: 'cv tres cantos', path: 'https://www.todovoleibol.com/images/escudos/cv-tres-cantos.jpg' },
{ id: 80, name: 'cv leganes', path: 'https://www.todovoleibol.com/images/escudos/cv-leganes.jpg' },
{ id: 81, name: 'club deportivo elemental voleibol daganzo de arriba', path: 'https://www.todovoleibol.com/images/escudos/club-deportivo-elemental-voleibol-daganzo-de-arriba.jpg' },
{ id: 82, name: 'club deportivo elemental colegio san jaime', path: 'https://www.todovoleibol.com/images/escudos/club-deportivo-elemental-colegio-san-jaime.jpg' },
{ id: 83, name: 'cv alcala', path: 'https://www.todovoleibol.com/images/escudos/cv-alcala.jpg' },
{ id: 84, name: 'colegio miramadrid', path: 'https://www.todovoleibol.com/images/escudos/colegio-miramadrid.jpg' },
{ id: 85, name: 'cde voleibol hispano usera', path: 'https://www.todovoleibol.com/images/escudos/cde-voleibol-hispano-usera.jpg' },
{ id: 86, name: 'cv collado villalba', path: 'https://www.todovoleibol.com/images/escudos/cv-collado-villalba.jpg' },
{ id: 87, name: 'ie university athletics', path: 'https://www.todovoleibol.com/images/escudos/ie-university-athletics.jpg' },
{ id: 88, name: 'club voleibol velilla', path: 'https://www.todovoleibol.com/images/escudos/club-voleibol-velilla.jpg' },
{ id: 89, name: 'cde vb moralzarzal', path: 'https://www.todovoleibol.com/images/escudos/cde-vb-moralzarzal.jpg' },
{ id: 90, name: 'cv alcobendas', path: 'https://www.todovoleibol.com/images/escudos/cv-alcobendas.jpg' },
{ id: 91, name: 'cv pinto', path: 'https://www.todovoleibol.com/images/escudos/cv-pinto.jpg' },
{ id: 92, name: 'cv las rozas', path: 'https://www.todovoleibol.com/images/escudos/cv-las-rozas.jpg' },
];

export default staticImages;